# Discription

In this data i have classified 4 types of roads which are good, poor, satisfactory and very poor using CNN. Upvote if you like my work.
Now lets get Started:

# First i am going to split data in x and y.

In [173]:
import os
import cv2

labels = ['good', 'poor', 'satisfactory', 'very_poor']

data_dir =  "data/sih_road_dataset/"

x = []
y = []
for label in labels:
    data = os.path.join(data_dir,label)
    for image in os.listdir(data):
        try:
            im = cv2.imread(os.path.join(data,image),cv2.IMREAD_COLOR)
            im = cv2.resize(im,(224,224))
            # Using the Canny filter with different parameters

            x.append(im)
            y.append(labels.index(label))


        except Exception as e:
            pass

In [174]:
# Just checking the legth of x and y
print(len(x))        
print(len(y))

1422
1422


# Changing list to array and rescaling the Data

In [175]:
import numpy as np
np.unique(y)
np.unique(x)

x = np.array(x)/255.0
y = np.array(y)

x.shape
y.shape

x = x.reshape(-1, 224, 224, 3)
x.shape
y = y.reshape(-1, 1)

# Turning y labels to categorical and Analysing Images

In [176]:
from tensorflow.keras.utils import to_categorical

y = to_categorical(y,4,)

from tensorflow.keras.preprocessing.image import ImageDataGenerator

datagenerator = ImageDataGenerator(
fill_mode= 'nearest',
horizontal_flip=False,
vertical_flip=False,
shear_range=0.1,
zoom_range = 0.1, # Randomly zoom image 
width_shift_range=0.2,  # randomly shift images horizontally (fraction of total width)
height_shift_range=0.2
)
datagenerator.fit(x)

# Splitting Data into train and test

In [177]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y)

# Using CNN (Convolutional neural Network)

In [178]:
import tensorflow as tf
model = tf.keras.Sequential([
tf.keras.layers.Conv2D(32,(5,5),padding ='same',strides=(2,2),activation='relu',input_shape=(224,224,3)),
tf.keras.layers.MaxPooling2D((2,2)),
tf.keras.layers.Conv2D(64,(5,5),padding ='same',strides=(2,2),activation='relu'),
tf.keras.layers.MaxPooling2D((2,2)),
tf.keras.layers.Conv2D(128,(5,5),padding ='same',strides=(2,2),activation='relu'),
tf.keras.layers.MaxPooling2D((2,2)),
tf.keras.layers.Conv2D(128,(5,5),padding ='same',strides=(2,2),activation='relu'),
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(256,activation='relu'),
tf.keras.layers.Dropout(0.2),
    
tf.keras.layers.Dense(4,activation='softmax')
])

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# Using early stopping and training the model

#### Note: EarlyStopping stop the model from overfitting.

In [215]:
earlystop = tf.keras.callbacks.EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

model.fit(datagenerator.flow(x_train,y_train,batch_size=28),epochs=20,callbacks=[earlystop],validation_data=datagenerator.flow(x_test,y_test))

Epoch 1/20
39/39 [==============================] - 14s 352ms/step - loss: 0.2654 - accuracy: 0.8940 - val_loss: 0.3340 - val_accuracy: 0.8652
Epoch 2/20
39/39 [==============================] - 20s 527ms/step - loss: 0.2960 - accuracy: 0.8902 - val_loss: 0.4134 - val_accuracy: 0.8427
Epoch 3/20
39/39 [==============================] - 17s 423ms/step - loss: 0.2843 - accuracy: 0.8856 - val_loss: 0.4027 - val_accuracy: 0.8258
Epoch 4/20
39/39 [==============================] - 16s 419ms/step - loss: 0.3015 - accuracy: 0.8724 - val_loss: 0.3424 - val_accuracy: 0.8792
Epoch 5/20
39/39 [==============================] - 16s 423ms/step - loss: 0.2614 - accuracy: 0.8996 - val_loss: 0.3000 - val_accuracy: 0.8820
Epoch 6/20
39/39 [==============================] - 16s 417ms/step - loss: 0.2553 - accuracy: 0.8996 - val_loss: 0.3207 - val_accuracy: 0.8736
Epoch 7/20
39/39 [==============================] - 16s 414ms/step - loss: 0.2476 - accuracy: 0.9006 - val_loss: 0.3096 - val_accuracy: 0.9017

# Plotting loss|val_loss to see if model overfitting or not

#### Note: If val_loss is higher then loss it means model is overfitting.

In [203]:
import pandas as pd
history = pd.DataFrame(model.history.history)
history[["loss", "val_loss"]].plot()

KeyError: "None of [Index(['loss', 'val_loss'], dtype='object')] are in the [columns]"

# At last evaluating the model to check accuracy

In [216]:
model.evaluate(x_test, y_test)

12/12 [==============================] - 1s 50ms/step - loss: 0.3791 - accuracy: 0.8876


[0.3790539801120758, 0.8876404762268066]

# And here is the Prediction of road

In [181]:
from PIL import Image
def convert_to_array(img):
    im = cv2.imread(img)
    img = Image.fromarray(im, 'RGB')
    image = img.resize((224, 224))
    return np.array(image)

In [182]:
def get_profile_name(label):
    if label==0:
        return "Good"
    if label==1:
        return "Poor"
    if label==2:
        return "Satisfactory"
    if label==3:
        return "Very_Poor"

In [183]:
def predict_profile(file):
    print("Predicting .................................")
    ar=convert_to_array(file)
    ar=ar/255
    a=[]
    a.append(ar)
    a=np.array(a)
    score=model.predict(a,verbose=1)
    print(score)
    label_index=np.argmax(score)
    print(label_index)
    acc=np.max(score)
    profile=get_profile_name(label_index)
    print(profile)
    print("The predicted profile is a "+profile+" with accuracy = "+str(acc))  
    return profile

## Predicting Very poor road

In [184]:
pre_image = "data/sih_road_dataset/very_poor/verypoor_014.jpg"

In [185]:
predict_profile(pre_image)

Predicting .................................
1/1 [==============================] - 0s 87ms/step
[[9.2844537e-05 3.1308343e-03 4.1629067e-03 9.9261343e-01]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.99261343


'Very_Poor'

## Predicting Good road

In [154]:
pre_image2 = "data/sih_road_dataset/good/good_040.jpg"


In [155]:
predict_profile(pre_image2)

Predicting .................................


AttributeError: 'NoneType' object has no attribute '__array_interface__'

## Predicting Satisfactory road

Note: in this data poor roads and satisfactory road are very similar to each other thats why model wont be able to predict or differentiate between those two images.

# Test pictures

In [204]:
import os
base_path = os.getcwd() + '/kaggle'

In [217]:
file_list = [filename for filename in os.listdir(base_path + '/input/') if not filename.startswith('.')]
count = 0
lenn = len(file_list)
dict = {'Poor' : 0, 'Good' : 0, 'Satisfactory' : 0, 'Very_Poor' : 0}
for file in file_list:
    path = 'kaggle/input/'+str(file)
    print(file)
    
#     ind = str(file)[-5]
    label = predict_profile(path)
#     if (ind==str(label).lower()[0]):
#         count+=1
    print()
    dict[label] += 1

AA_10800.jpeg
Predicting .................................
1/1 [==============================] - 0s 13ms/step
[[0.15792327 0.1918445  0.46525317 0.18497899]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.46525317

AA_10810.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.1316077  0.1750067  0.48738536 0.20600024]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.48738536

AB_1000.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.07890265 0.13726565 0.42790097 0.35593078]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.42790097

AB_1010.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0982977  0.15055062 0.5882055  0.16294618]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5882055

AB_1020.jpeg
Predicting ...........

1/1 [==============================] - 0s 18ms/step
[[0.01439754 0.03408246 0.4260982  0.52542174]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.52542174

AC_15980.jpeg
Predicting .................................
1/1 [==============================] - 0s 21ms/step
[[0.06166143 0.09465142 0.3791094  0.4645778 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.4645778

AC_16000.jpeg
Predicting .................................
1/1 [==============================] - 0s 21ms/step
[[0.07937609 0.22913589 0.5856665  0.10582159]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5856665

AC_16020.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.05999594 0.3774     0.49091038 0.07169374]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.49091038

AC_16030.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms

1/1 [==============================] - 0s 10ms/step
[[0.04212789 0.07210893 0.6502086  0.23555464]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6502086

AC_23040.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.03704842 0.0718324  0.5029851  0.3881341 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5029851

AC_23050.jpeg
Predicting .................................
1/1 [==============================] - 0s 19ms/step
[[0.03537909 0.08966338 0.44442132 0.43053618]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.44442132

AC_23060.jpeg
Predicting .................................
1/1 [==============================] - 0s 18ms/step
[[0.01374461 0.04970018 0.20309605 0.7334592 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7334592

AC_23070.jpeg
Predicting .................................
1/1 [==============================] - 0s

1/1 [==============================] - 0s 20ms/step
[[0.00640098 0.3631294  0.6241692  0.00630047]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6241692

AC_2970.jpeg
Predicting .................................
1/1 [==============================] - 0s 12ms/step
[[0.01629569 0.20195849 0.75238186 0.02936396]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.75238186

AC_2980.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.00534056 0.5098732  0.47830284 0.00648348]]
1
Poor
The predicted profile is a Poor with accuracy = 0.5098732

AC_31150.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.01294373 0.55441046 0.37555826 0.05708752]]
1
Poor
The predicted profile is a Poor with accuracy = 0.55441046

AC_31160.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.01110422 0.0


AC_3980.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.01459949 0.33651727 0.5831604  0.0657229 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5831604

AC_3990.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.01696777 0.39167225 0.5866949  0.00466511]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5866949

AC_4000.jpeg
Predicting .................................
1/1 [==============================] - 0s 11ms/step
[[0.01619453 0.4601986  0.5204511  0.00315577]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5204511

AC_4020.jpeg
Predicting .................................
1/1 [==============================] - 0s 21ms/step
[[0.01982585 0.37250564 0.5126345  0.09503393]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5126345

AC_410.jpeg
Predicting ................

1/1 [==============================] - 0s 20ms/step
[[0.05711767 0.11547423 0.4847623  0.34264585]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4847623

AC_4880.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.20693097 0.2573078  0.40888378 0.12687744]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.40888378

AC_4890.jpeg
Predicting .................................
1/1 [==============================] - 0s 13ms/step
[[0.03883071 0.06550128 0.63130593 0.26436204]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.63130593

AC_4900.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.05532052 0.15796976 0.26983428 0.51687545]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.51687545

AC_4910.jpeg
Predicting .................................
1/1 [==============================] - 0s 9

1/1 [==============================] - 0s 19ms/step
[[0.04809764 0.1300411  0.31759164 0.5042696 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5042696

AC_8290.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.06500846 0.15472452 0.32676527 0.45350176]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.45350176

AC_8810.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.00286014 0.0174708  0.04658548 0.9330836 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9330836

AC_8820.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.00400281 0.0327743  0.05801994 0.9052029 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9052029

AC_8830.jpeg
Predicting .................................
1/1 [==============================] - 0s 14ms/step
[[0.0047838

1/1 [==============================] - 0s 20ms/step
[[0.02993277 0.09583458 0.30296403 0.5712686 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5712686

AD_14550.jpeg
Predicting .................................
1/1 [==============================] - 0s 13ms/step
[[0.05278054 0.3998556  0.49302313 0.0543407 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.49302313

AD_14560.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.11950088 0.2841308  0.4700126  0.12635571]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4700126

AD_14570.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.05966131 0.37438813 0.378617   0.18733352]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.378617

AD_14650.jpeg
Predicting .................................
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 20ms/step
[[0.07177811 0.3173404  0.6083642  0.00251723]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6083642

AD_29600.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.21441042 0.3041369  0.44815058 0.03330215]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.44815058

AD_29620.jpeg
Predicting .................................
1/1 [==============================] - 0s 14ms/step
[[0.11692358 0.33339483 0.4669323  0.08274931]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4669323

AD_29810.jpeg
Predicting .................................
1/1 [==============================] - 0s 25ms/step
[[0.0151022  0.5807491  0.40036842 0.00378033]]
1
Poor
The predicted profile is a Poor with accuracy = 0.5807491

AD_29820.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step

[[0.15491335 0.21276213 0.40818053 0.224144  ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.40818053

AD_32820.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.14642945 0.13802497 0.6352495  0.08029603]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6352495

AD_32840.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.20207593 0.17153555 0.5315169  0.09487156]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5315169

AD_4690.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.14519791 0.22365624 0.4037163  0.22742952]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4037163

AD_4700.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.09428301 0.16779473 0.40732008 0.

1/1 [==============================] - 0s 15ms/step
[[0.01202678 0.08519401 0.19386187 0.7089174 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7089174

AF_110.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.05717209 0.20155144 0.4070228  0.33425364]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4070228

AF_130.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.0500458  0.18836969 0.38267165 0.37891293]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.38267165

AF_14930.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.08952427 0.17407131 0.35274088 0.38366354]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.38366354

AF_14940.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/ste

1/1 [==============================] - 0s 16ms/step
[[0.1688807  0.212168   0.5362467  0.08270457]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5362467

AH_15320.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.09945299 0.14597833 0.72070074 0.03386783]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.72070074

AH_3090.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.01633524 0.04162603 0.78280264 0.15923609]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.78280264

AH_3100.jpeg
Predicting .................................
1/1 [==============================] - 0s 27ms/step
[[0.01842589 0.06398777 0.55969125 0.35789508]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.55969125

AH_3110.jpeg
Predicting .................................
1/1 [==============================]

1/1 [==============================] - 0s 14ms/step
[[0.18112896 0.18807116 0.5840159  0.04678387]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5840159

AM_4480.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.08718427 0.09360472 0.79352534 0.02568564]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.79352534

AM_4500.jpeg
Predicting .................................
1/1 [==============================] - 0s 19ms/step
[[0.3922035  0.28315204 0.29430145 0.03034301]]
0
Good
The predicted profile is a Good with accuracy = 0.3922035

AM_4520.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.30479968 0.20944317 0.45291144 0.0328458 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.45291144

AM_4540.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[

1/1 [==============================] - 0s 25ms/step
[[0.02928352 0.0678904  0.48557374 0.41725233]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.48557374

AX_10540.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.05793221 0.13855478 0.5024988  0.30101413]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5024988

AX_1400.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.10230367 0.22583671 0.2851707  0.38668895]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.38668895

AX_1420.jpeg
Predicting .................................
1/1 [==============================] - 0s 14ms/step
[[0.03923015 0.13771397 0.20909517 0.61396074]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.61396074

AX_1490.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/s

1/1 [==============================] - 0s 16ms/step
[[0.06190329 0.10107032 0.5710936  0.26593283]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5710936

AX_3310.jpeg
Predicting .................................
1/1 [==============================] - 0s 21ms/step
[[0.04558691 0.06470539 0.48895797 0.40074977]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.48895797

AX_3330.jpeg
Predicting .................................
1/1 [==============================] - 0s 14ms/step
[[0.08808513 0.09759708 0.51655483 0.297763  ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.51655483

AX_3620.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.03098181 0.16351901 0.36656985 0.43892935]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.43892935

AX_3660.jpeg
Predicting .................................
1/1 [==============================] - 0s 2

1/1 [==============================] - 0s 21ms/step
[[0.00291035 0.02674879 0.02331825 0.9470226 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9470226

AX_5230.jpeg
Predicting .................................
1/1 [==============================] - 0s 18ms/step
[[0.00588213 0.05896709 0.03271686 0.90243393]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.90243393

AX_5250.jpeg
Predicting .................................
1/1 [==============================] - 0s 12ms/step
[[0.03856926 0.1404421  0.11463299 0.7063557 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7063557

AX_5260.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.06547105 0.28537175 0.14254229 0.50661486]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.50661486

AX_5300.jpeg
Predicting .................................
1/1 [==============================] - 0s 8ms/step
[[0.0421612

1/1 [==============================] - 0s 22ms/step
[[0.1027162  0.2866869  0.30810082 0.30249608]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.30810082

AX_6990.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.13269213 0.32032472 0.31093735 0.23604576]]
1
Poor
The predicted profile is a Poor with accuracy = 0.32032472

AX_700.jpeg
Predicting .................................
1/1 [==============================] - 0s 19ms/step
[[0.20595261 0.3244494  0.38915512 0.08044294]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.38915512

AX_7010.jpeg
Predicting .................................
1/1 [==============================] - 0s 18ms/step
[[0.09537467 0.20543933 0.29685065 0.40233535]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.40233535

AX_7030.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.080

1/1 [==============================] - 0s 15ms/step
[[0.08073847 0.2760984  0.41334024 0.22982289]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.41334024

AX_8790.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.09425562 0.26711652 0.47531208 0.16331574]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.47531208

AX_880.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.07567848 0.09071707 0.43656778 0.39703658]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.43656778

AX_8810.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.04659462 0.22255869 0.5409036  0.18994302]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5409036

AX_8830.jpeg
Predicting .................................
1/1 [==============================] -

1/1 [==============================] - 0s 20ms/step
[[0.51647604 0.09786329 0.38464954 0.00101114]]
0
Good
The predicted profile is a Good with accuracy = 0.51647604

BF_1390.jpeg
Predicting .................................
1/1 [==============================] - 0s 27ms/step
[[0.3139727  0.38737497 0.23716946 0.0614829 ]]
1
Poor
The predicted profile is a Poor with accuracy = 0.38737497

BF_1400.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.30978188 0.44178796 0.20585592 0.04257433]]
1
Poor
The predicted profile is a Poor with accuracy = 0.44178796

BF_1410.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.32934755 0.5080456  0.13213886 0.03046796]]
1
Poor
The predicted profile is a Poor with accuracy = 0.5080456

BF_20.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[8.1486657e-02 1.0420369e-02 9.0784556e-01 2.47475

1/1 [==============================] - 0s 15ms/step
[[0.56636536 0.08187544 0.3458691  0.00589009]]
0
Good
The predicted profile is a Good with accuracy = 0.56636536

BG_460.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.2229704  0.14948948 0.6255203  0.00201985]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6255203

BG_470.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.13295355 0.1176147  0.74725693 0.00217477]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.74725693

BG_480.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.09162544 0.08421194 0.8214153  0.0027473 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.8214153

BG_980.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.41

1/1 [==============================] - 0s 15ms/step
[[0.06585636 0.01199373 0.9186854  0.00346452]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.9186854

BH_3480.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.05141415 0.0056439  0.94047666 0.00246532]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.94047666

BH_5380.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.1921319  0.26052204 0.34551728 0.20182875]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.34551728

BH_5390.jpeg
Predicting .................................
1/1 [==============================] - 0s 14ms/step
[[0.22528204 0.3073145  0.30832794 0.1590756 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.30832794

BH_5400.jpeg
Predicting .................................
1/1 [==============================] 

1/1 [==============================] - 0s 10ms/step
[[0.02794967 0.22092879 0.25193802 0.49918357]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.49918357

BI_6160.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.06537146 0.1842587  0.29842275 0.45194715]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.45194715

BI_9350.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[8.8464677e-01 6.7293748e-02 4.7427587e-02 6.3195633e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.8846468

BI_9360.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.8097328  0.09867015 0.0902653  0.00133171]]
0
Good
The predicted profile is a Good with accuracy = 0.8097328

BI_9370.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.7552577  0.163

1/1 [==============================] - 0s 20ms/step
[[0.72607    0.22319283 0.04769617 0.00304102]]
0
Good
The predicted profile is a Good with accuracy = 0.72607

BK_2640.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.75616676 0.22116975 0.02139213 0.00127129]]
0
Good
The predicted profile is a Good with accuracy = 0.75616676

BK_2650.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.7767749  0.19419606 0.02760883 0.00142021]]
0
Good
The predicted profile is a Good with accuracy = 0.7767749

BK_2670.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.52432644 0.31649125 0.15549669 0.00368558]]
0
Good
The predicted profile is a Good with accuracy = 0.52432644

BK_2680.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.32371208 0.35956204 0.31031144 0.00641452]]
1
Po

1/1 [==============================] - 0s 15ms/step
[[0.02763753 0.15356989 0.22884813 0.58994436]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.58994436

BL_2690.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.0336327  0.19770262 0.27677298 0.49189177]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.49189177

BL_2700.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.03415714 0.2768204  0.3486109  0.34041157]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3486109

BL_2710.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.08022005 0.32025984 0.4455725  0.15394755]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4455725

BL_4650.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/ste

1/1 [==============================] - 0s 20ms/step
[[0.10247316 0.09440133 0.4351023  0.36802322]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4351023

B_2540.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.2945407  0.19719854 0.37383735 0.13442348]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.37383735

B_2630.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[8.7805277e-01 1.1491817e-01 6.7272834e-03 3.0178213e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.8780528

B_2720.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.02151371 0.1325508  0.19094393 0.6549916 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6549916

B_2780.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[

1/1 [==============================] - 0s 10ms/step
[[0.04033105 0.04698213 0.6828334  0.22985339]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6828334

C_2690.jpeg
Predicting .................................
1/1 [==============================] - 0s 13ms/step
[[0.01922946 0.03468893 0.4866954  0.45938626]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4866954

C_2700.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.00395383 0.01761741 0.12405352 0.85437524]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.85437524

C_2750.jpeg
Predicting .................................
1/1 [==============================] - 0s 21ms/step
[[0.00187201 0.01130265 0.06615805 0.92066723]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.92066723

C_2800.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[

1/1 [==============================] - 0s 15ms/step
[[0.10955321 0.21765223 0.4763771  0.19641745]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4763771

D_11080.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.07664534 0.69356775 0.11924156 0.11054528]]
1
Poor
The predicted profile is a Poor with accuracy = 0.69356775

D_11150.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.29240903 0.5201223  0.16544265 0.02202611]]
1
Poor
The predicted profile is a Poor with accuracy = 0.5201223

D_11180.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.16988108 0.69604707 0.11793916 0.01613275]]
1
Poor
The predicted profile is a Poor with accuracy = 0.69604707

D_11240.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.39871007 0.4648785  0.1270164 

1/1 [==============================] - 0s 16ms/step
[[6.4975763e-04 1.0759103e-02 4.7404975e-02 9.4118619e-01]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9411862

D_23880.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.03385089 0.48302266 0.37409306 0.10903338]]
1
Poor
The predicted profile is a Poor with accuracy = 0.48302266

D_23890.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.02920154 0.58583814 0.31236625 0.07259409]]
1
Poor
The predicted profile is a Poor with accuracy = 0.58583814

D_23900.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.03156905 0.5541437  0.3472856  0.0670016 ]]
1
Poor
The predicted profile is a Poor with accuracy = 0.5541437

D_23960.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0241246  0.62338567 0.23

1/1 [==============================] - 0s 20ms/step
[[8.8565372e-04 8.2577672e-03 2.9427513e-02 9.6142906e-01]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.96142906

F_11290.jpeg
Predicting .................................
1/1 [==============================] - 0s 19ms/step
[[0.00246575 0.01887085 0.03347757 0.9451859 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9451859

F_11300.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.00457772 0.02819526 0.05037351 0.9168535 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9168535

F_11310.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.00393507 0.02859627 0.03430385 0.9331648 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9331648

F_11400.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step

1/1 [==============================] - 0s 11ms/step
[[0.07547701 0.14451714 0.35104275 0.42896312]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.42896312

F_16870.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.02427227 0.08530983 0.16819142 0.72222644]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.72222644

F_17030.jpeg
Predicting .................................
1/1 [==============================] - 0s 21ms/step
[[0.07866629 0.16610137 0.31098914 0.44424316]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.44424316

F_17080.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.04761465 0.12283096 0.22244534 0.60710907]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.60710907

F_17130.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.0052

1/1 [==============================] - 0s 9ms/step
[[0.33637777 0.45823854 0.10675149 0.09863224]]
1
Poor
The predicted profile is a Poor with accuracy = 0.45823854

F_20120.jpeg
Predicting .................................
1/1 [==============================] - 0s 13ms/step
[[0.39740506 0.502227   0.05634146 0.04402645]]
1
Poor
The predicted profile is a Poor with accuracy = 0.502227

F_20340.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.28151083 0.28445706 0.31334296 0.1206892 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.31334296

F_20410.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.16377592 0.265512   0.47883824 0.09187386]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.47883824

F_20450.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.21048087 0.2731

1/1 [==============================] - 0s 15ms/step
[[0.30311117 0.15565674 0.5127781  0.02845398]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5127781

F_29700.jpeg
Predicting .................................
1/1 [==============================] - 0s 9ms/step
[[0.5338924  0.2005516  0.2505725  0.01498349]]
0
Good
The predicted profile is a Good with accuracy = 0.5338924

F_29930.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.03373453 0.08685203 0.24097478 0.6384387 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6384387

F_30000.jpeg
Predicting .................................
1/1 [==============================] - 0s 8ms/step
[[0.05463507 0.09927829 0.7399365  0.10615014]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.7399365

F_30070.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.28206155

1/1 [==============================] - 0s 15ms/step
[[0.0071167  0.03061887 0.28295293 0.6793115 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6793115

F_35180.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.03716555 0.31185508 0.3669626  0.28401682]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3669626

F_35240.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.0266908  0.05018149 0.38517952 0.5379482 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5379482

F_35260.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0.0361935  0.0512012  0.39812145 0.51448387]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.51448387

F_35330.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.0

1/1 [==============================] - 0s 15ms/step
[[0.09156315 0.14794348 0.6078462  0.15264715]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6078462

F_39560.jpeg
Predicting .................................
1/1 [==============================] - 0s 9ms/step
[[0.08819206 0.17573713 0.43321863 0.30285218]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.43321863

F_39590.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.18050393 0.64933825 0.14717107 0.02298674]]
1
Poor
The predicted profile is a Poor with accuracy = 0.64933825

F_39640.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.05087326 0.13952601 0.51398367 0.29561707]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.51398367

F_3970.jpeg
Predicting .................................
1/1 [==============================] - 0s 10ms/step
[[0

1/1 [==============================] - 0s 15ms/step
[[0.05973195 0.43744454 0.4062378  0.09658577]]
1
Poor
The predicted profile is a Poor with accuracy = 0.43744454

F_42030.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.14006555 0.10270298 0.5940495  0.16318187]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5940495

F_42290.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.08582841 0.06726253 0.7719257  0.07498335]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.7719257

F_42330.jpeg
Predicting .................................
1/1 [==============================] - 0s 14ms/step
[[0.05005169 0.04734538 0.67555    0.227053  ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.67555

F_42370.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.0

1/1 [==============================] - 0s 34ms/step
[[0.06901003 0.29067326 0.3691867  0.27113003]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3691867

F_46970.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01572402 0.03381376 0.3964462  0.5540161 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5540161

F_47240.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.00129852 0.00450005 0.02476604 0.9694354 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9694354

F_47530.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02288262 0.03968056 0.3292201  0.60821676]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.60821676

F_47660.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0

1/1 [==============================] - 0s 16ms/step
[[0.09651843 0.42681497 0.22296101 0.25370562]]
1
Poor
The predicted profile is a Poor with accuracy = 0.42681497

F_53150.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0755542  0.20527121 0.280033   0.43914154]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.43914154

F_53160.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.04450334 0.15719254 0.19587462 0.6024295 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6024295

F_53280.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.07942826 0.15124711 0.27668434 0.49264017]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.49264017

F_53300.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.17439698 0.2596

1/1 [==============================] - 0s 16ms/step
[[0.08153956 0.09413997 0.56244904 0.26187146]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.56244904

F_8470.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.26380733 0.13459092 0.5278187  0.0737831 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5278187

F_8550.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.3938389  0.10578659 0.39314032 0.1072342 ]]
0
Good
The predicted profile is a Good with accuracy = 0.3938389

F_8560.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.6186219  0.1677573  0.13145278 0.08216809]]
0
Good
The predicted profile is a Good with accuracy = 0.6186219

F_8570.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.4581031  0.15819018

1/1 [==============================] - 0s 16ms/step
[[0.01307447 0.05065074 0.06149079 0.874784  ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.874784

G_2560.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0026096  0.01646764 0.06764311 0.9132796 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9132796

G_2580.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.06512622 0.10777885 0.39204228 0.4350527 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.4350527

G_2620.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.09266094 0.10456271 0.52902687 0.27374938]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.52902687

G_2660.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.257383

1/1 [==============================] - 0s 16ms/step
[[0.07696565 0.3545799  0.5029246  0.06552977]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5029246

H_3210.jpeg
Predicting .................................
1/1 [==============================] - 0s 29ms/step
[[0.11624388 0.2172353  0.45752624 0.20899467]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.45752624

H_3220.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.12476894 0.23188601 0.46371725 0.17962782]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.46371725

H_3290.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.00901598 0.07530063 0.1301048  0.7855786 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7855786

H_3450.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/s

1/1 [==============================] - 0s 24ms/step
[[0.02184563 0.06202965 0.3925386  0.52358615]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.52358615

H_5700.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01053222 0.03635575 0.12136416 0.83174783]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.83174783

H_5760.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.04344511 0.04872714 0.3223307  0.58549696]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.58549696

H_5810.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00607192 0.01478947 0.07397448 0.9051642 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9051642

H_6070.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00820256 

1/1 [==============================] - 0s 16ms/step
[[0.02065753 0.40650007 0.4360963  0.13674611]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4360963

J_4020.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01145769 0.14304319 0.23805375 0.60744536]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.60744536

J_4030.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00441564 0.08014013 0.15233575 0.7631085 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7631085

J_4040.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.01301235 0.25073662 0.3242022  0.41204885]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.41204885

J_4050.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0133

1/1 [==============================] - 0s 17ms/step
[[0.03785804 0.4489504  0.36742347 0.1457681 ]]
1
Poor
The predicted profile is a Poor with accuracy = 0.4489504

K_12130.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[8.0724746e-01 1.8639599e-01 5.6059626e-03 7.5057929e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.80724746

K_12310.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[7.9686326e-01 1.9097626e-01 1.1673008e-02 4.8752749e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.79686326

K_12380.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.09112378 0.09841798 0.72092855 0.08952963]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.72092855

K_12510.jpeg
Predicting .................................
1/1 [==============================] - 0s 18ms/step
[[0.10106

1/1 [==============================] - 0s 28ms/step
[[0.04196416 0.17366527 0.48675686 0.2976137 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.48675686

K_13590.jpeg
Predicting .................................
1/1 [==============================] - 0s 15ms/step
[[0.05604262 0.22240402 0.4593847  0.26216865]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4593847

K_13630.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0354007  0.08325702 0.79301757 0.08832473]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.79301757

K_13640.jpeg
Predicting .................................
1/1 [==============================] - 0s 18ms/step
[[0.04237216 0.08097753 0.8204276  0.05622264]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.8204276

K_14040.jpeg
Predicting .................................
1/1 [==============================] -

1/1 [==============================] - 0s 16ms/step
[[0.01934218 0.06154936 0.4327938  0.48631465]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.48631465

K_2910.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01915444 0.06271062 0.49104506 0.42708984]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.49104506

K_2980.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00378098 0.02519451 0.07957387 0.8914507 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8914507

K_3030.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00313419 0.01948895 0.12514171 0.8522352 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8522352

K_3050.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.0017

1/1 [==============================] - 0s 16ms/step
[[8.674400e-01 6.855361e-02 6.350557e-02 5.007439e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.86744

K_8360.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[9.1239303e-01 7.5671390e-02 1.1711626e-02 2.2395421e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.91239303

K_8380.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[9.6275353e-01 1.7867832e-02 1.9356268e-02 2.2384740e-05]]
0
Good
The predicted profile is a Good with accuracy = 0.96275353

K_8400.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[7.9003239e-01 1.9891934e-02 1.8995853e-01 1.1714678e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.7900324

K_8410.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[5.0121993e

1/1 [==============================] - 0s 24ms/step
[[0.06332543 0.08708742 0.7514889  0.09809814]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.7514889

L_7530.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.01782079 0.11731564 0.74293315 0.12193049]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.74293315

L_7540.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0220594  0.16324371 0.705873   0.10882396]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.705873

L_7550.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.02297015 0.3157807  0.5749339  0.08631528]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5749339

L_7590.jpeg
Predicting .................................
1/1 [==============================] - 0s 16

1/1 [==============================] - 0s 16ms/step
[[0.02010319 0.06324343 0.4888056  0.4278478 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4888056

N_31660.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.00532509 0.13468216 0.10492274 0.7550699 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7550699

N_31770.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.05234436 0.05926867 0.57434404 0.31404287]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.57434404

N_32300.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.43432134 0.06821325 0.4940608  0.00340464]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4940608

N_3240.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms

1/1 [==============================] - 0s 16ms/step
[[0.03639584 0.06952544 0.7250786  0.16900016]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.7250786

N_4710.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.01876629 0.09271653 0.32970896 0.55880827]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.55880827

N_50.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01175979 0.3507583  0.41483602 0.22264595]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.41483602

N_520.jpeg
Predicting .................................
1/1 [==============================] - 0s 13ms/step
[[0.03152575 0.41289037 0.499535   0.05604884]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.499535

O_10090.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step

1/1 [==============================] - 0s 24ms/step
[[0.22421478 0.28227225 0.4213894  0.07212359]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4213894

O_3610.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.25376633 0.2903141  0.3802206  0.0756989 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3802206

O_3620.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.26045713 0.29242477 0.3781682  0.06894989]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3781682

O_3630.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.31330487 0.28118846 0.343777   0.06172968]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.343777

O_3640.jpeg
Predicting .................................
1/1 [==============================] - 0s 24m

1/1 [==============================] - 0s 17ms/step
[[0.4454159  0.41824675 0.12222946 0.01410789]]
0
Good
The predicted profile is a Good with accuracy = 0.4454159

O_630.jpeg
Predicting .................................
1/1 [==============================] - 0s 18ms/step
[[0.44039556 0.45035908 0.09874578 0.01049949]]
1
Poor
The predicted profile is a Poor with accuracy = 0.45035908

O_640.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.42527688 0.47096664 0.0942305  0.00952598]]
1
Poor
The predicted profile is a Poor with accuracy = 0.47096664

O_650.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.4750413  0.43893144 0.08013343 0.0058938 ]]
0
Good
The predicted profile is a Good with accuracy = 0.4750413

O_660.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.49473098 0.44402593 0.05721753 0.00402551]]
0
Good
The

1/1 [==============================] - 0s 18ms/step
[[0.04069011 0.14636526 0.5037115  0.30923304]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5037115

P_11940.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.05340349 0.23348816 0.49966595 0.21344236]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.49966595

P_11950.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.04527329 0.17813414 0.3799291  0.39666343]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.39666343

P_11960.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.03436987 0.10053535 0.28929424 0.5758005 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5758005

P_11970.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/ste

1/1 [==============================] - 0s 12ms/step
[[0.06463871 0.35157123 0.30624887 0.27754113]]
1
Poor
The predicted profile is a Poor with accuracy = 0.35157123

P_25910.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[1.3738790e-02 9.7680455e-01 9.3110856e-03 1.4556662e-04]]
1
Poor
The predicted profile is a Poor with accuracy = 0.97680455

P_25920.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[4.0198914e-03 9.9281812e-01 3.0996199e-03 6.2373736e-05]]
1
Poor
The predicted profile is a Poor with accuracy = 0.9928181

P_25980.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.08813785 0.08082087 0.7612385  0.06980272]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.7612385

P_25990.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.124377

1/1 [==============================] - 0s 16ms/step
[[0.14096305 0.23529898 0.56359327 0.06014471]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.56359327

P_28190.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.21094276 0.3183473  0.44700688 0.02370306]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.44700688

P_28230.jpeg
Predicting .................................
1/1 [==============================] - 0s 17ms/step
[[0.09854907 0.11495007 0.6948929  0.09160791]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6948929

P_28240.jpeg
Predicting .................................
1/1 [==============================] - 0s 28ms/step
[[0.10984923 0.13562465 0.68497914 0.069547  ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.68497914

P_28250.jpeg
Predicting .................................
1/1 [==============================] 

1/1 [==============================] - 0s 16ms/step
[[0.268097   0.62481946 0.08835387 0.01872965]]
1
Poor
The predicted profile is a Poor with accuracy = 0.62481946

P_29800.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.27527502 0.6233885  0.08458017 0.01675626]]
1
Poor
The predicted profile is a Poor with accuracy = 0.6233885

P_29820.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.2888948  0.6170332  0.07610599 0.0179661 ]]
1
Poor
The predicted profile is a Poor with accuracy = 0.6170332

P_30.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.09621218 0.0351857  0.8353411  0.03326103]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.8353411

P_300.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.7883308  0.08633732 0.12426994 0.001

1/1 [==============================] - 0s 16ms/step
[[0.12006549 0.14334245 0.69484407 0.04174799]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.69484407

P_31880.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.15188485 0.25173947 0.5395534  0.05682227]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5395534

P_31890.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.12484426 0.26794574 0.5321107  0.07509937]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5321107

P_31930.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.09652368 0.38584074 0.46645674 0.05117877]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.46645674

P_31940.jpeg
Predicting .................................
1/1 [==============================] -

1/1 [==============================] - 0s 10ms/step
[[0.09013432 0.4655178  0.29629397 0.14805397]]
1
Poor
The predicted profile is a Poor with accuracy = 0.4655178

P_32510.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.09618095 0.41140214 0.2981621  0.19425482]]
1
Poor
The predicted profile is a Poor with accuracy = 0.41140214

P_32530.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.085128   0.29548848 0.34205124 0.27733234]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.34205124

P_32540.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.07472861 0.23427832 0.3714829  0.31951016]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3714829

P_32590.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.0670885  0.176

1/1 [==============================] - 0s 25ms/step
[[0.00585821 0.03276576 0.07899515 0.8823809 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8823809

P_34850.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01759456 0.06119364 0.15437903 0.7668327 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7668327

P_34860.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01943081 0.06033354 0.23636357 0.68387204]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.68387204

P_34950.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03429681 0.12860648 0.30587405 0.5312227 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5312227

P_34970.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0222819

1/1 [==============================] - 0s 16ms/step
[[0.08524476 0.17540307 0.5603766  0.17897555]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5603766

P_38680.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.10225631 0.25075445 0.5243355  0.12265376]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5243355

P_38690.jpeg
Predicting .................................
1/1 [==============================] - 0s 28ms/step
[[0.07854611 0.16993593 0.6111001  0.14041793]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6111001

P_390.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.460036   0.5109838  0.02741739 0.00156283]]
1
Poor
The predicted profile is a Poor with accuracy = 0.5109838

P_39340.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01

1/1 [==============================] - 0s 23ms/step
[[0.05058398 0.13150842 0.24366961 0.57423794]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.57423794

P_53910.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02452805 0.08895709 0.18906869 0.6974461 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6974461

P_6020.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.31932142 0.520369   0.09593453 0.06437514]]
1
Poor
The predicted profile is a Poor with accuracy = 0.520369

P_6030.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.3719637  0.49951974 0.07859899 0.04991749]]
1
Poor
The predicted profile is a Poor with accuracy = 0.49951974

P_6040.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.20022693 0.37806165 0.16929354

1/1 [==============================] - 0s 16ms/step
[[0.06304863 0.20121193 0.34258458 0.39315492]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.39315492

Q_10290.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.09051158 0.20096502 0.3224894  0.38603398]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.38603398

Q_10800.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.05007607 0.13293485 0.40386793 0.41312104]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.41312104

Q_10810.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03961676 0.1611728  0.4316251  0.3675854 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4316251

Q_10830.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0

1/1 [==============================] - 0s 24ms/step
[[0.34934273 0.15343414 0.4341963  0.06302677]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4341963

Q_140.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.21326457 0.11258012 0.6083781  0.06577725]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6083781

Q_14200.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03099601 0.17986554 0.28195062 0.50718784]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.50718784

Q_14220.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02562192 0.10102891 0.24812263 0.6252265 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6252265

Q_14240.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[

1/1 [==============================] - 0s 17ms/step
[[0.26736286 0.2674169  0.4354147  0.02980562]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4354147

Q_5140.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.23324677 0.3277899  0.4136897  0.02527358]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4136897

Q_5150.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.22360493 0.3016757  0.44507802 0.02964135]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.44507802

Q_5320.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.08962472 0.29007465 0.5309213  0.08937944]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5309213

Q_5340.jpeg
Predicting .................................
1/1 [==============================] - 0s 1

1/1 [==============================] - 0s 16ms/step
[[0.11364602 0.17200494 0.31598955 0.3983595 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.3983595

Q_7620.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.11282354 0.15535301 0.37326592 0.3585576 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.37326592

Q_7630.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.09951431 0.15724984 0.35633487 0.386901  ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.386901

Q_7640.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.113064   0.18575557 0.38042137 0.320759  ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.38042137

Q_7650.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0

1/1 [==============================] - 0s 16ms/step
[[0.28784558 0.33189973 0.33075115 0.04950344]]
1
Poor
The predicted profile is a Poor with accuracy = 0.33189973

R_19650.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.2605617  0.3980058  0.2908195  0.05061292]]
1
Poor
The predicted profile is a Poor with accuracy = 0.3980058

R_20160.jpeg
Predicting .................................
1/1 [==============================] - 0s 19ms/step
[[0.05680839 0.1071621  0.5027989  0.33323058]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5027989

R_20180.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.08041808 0.15078183 0.44595397 0.3228461 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.44595397

R_20190.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.10487384 0.165

1/1 [==============================] - 0s 16ms/step
[[0.03635176 0.15792766 0.26687774 0.5388428 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5388428

R_6170.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02477754 0.11802821 0.22777064 0.6294235 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6294235

R_6390.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00876384 0.037667   0.10881339 0.84475565]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.84475565

R_6400.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00645577 0.02964787 0.08719607 0.87670034]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.87670034

R_6420.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.00320081 0

1/1 [==============================] - 0s 16ms/step
[[0.0303889  0.06786913 0.35847685 0.5432651 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5432651

S_19070.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01516136 0.04106751 0.27791882 0.66585225]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.66585225

S_19270.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.06235141 0.10141626 0.3551202  0.48111215]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.48111215

S_19280.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03069908 0.06565704 0.26391333 0.6397306 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6397306

S_19290.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.067804

1/1 [==============================] - 0s 16ms/step
[[0.00799797 0.02773437 0.16850935 0.7957583 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7957583

U_11190.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00983287 0.03331576 0.1666721  0.79017925]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.79017925

U_11200.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00663962 0.02730129 0.13811082 0.8279483 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8279483

U_11560.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.27853057 0.38245448 0.22043352 0.11858144]]
1
Poor
The predicted profile is a Poor with accuracy = 0.38245448

U_11570.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.14407103 0.30053

1/1 [==============================] - 0s 16ms/step
[[0.0212869  0.02206475 0.1785889  0.7780594 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7780594

U_7360.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0347908  0.02582905 0.18807557 0.75130457]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.75130457

U_7770.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01216367 0.02850454 0.13627626 0.8230555 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8230555

U_7780.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.04646441 0.07456166 0.28873917 0.59023476]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.59023476

U_7790.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.01923927 0

1/1 [==============================] - 0s 16ms/step
[[0.03975458 0.46306154 0.4400888  0.05709505]]
1
Poor
The predicted profile is a Poor with accuracy = 0.46306154

V_14870.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03337619 0.44514096 0.45130643 0.07017635]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.45130643

V_14930.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02648866 0.4622919  0.40165395 0.10956548]]
1
Poor
The predicted profile is a Poor with accuracy = 0.4622919

V_14940.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01370492 0.45868966 0.41652185 0.11108357]]
1
Poor
The predicted profile is a Poor with accuracy = 0.45868966

V_14950.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00829075 0.14965886 0.1890422

1/1 [==============================] - 0s 24ms/step
[[6.5312022e-01 4.7854275e-02 2.9860303e-01 4.2248008e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.6531202

X_10260.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.49618796 0.04151844 0.46135223 0.00094132]]
0
Good
The predicted profile is a Good with accuracy = 0.49618796

X_10270.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[7.6102090e-01 4.4392951e-02 1.9422710e-01 3.5903795e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.7610209

X_10280.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[6.38740599e-01 1.35868937e-02 3.47551644e-01 1.20824334e-04]]
0
Good
The predicted profile is a Good with accuracy = 0.6387406

X_10430.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0756828

1/1 [==============================] - 0s 16ms/step
[[0.01677164 0.3237065  0.5132342  0.14628759]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5132342

X_11170.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02044744 0.3734816  0.53397197 0.07209893]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.53397197

X_11180.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02184815 0.3788838  0.5551864  0.04408165]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5551864

X_11190.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01846286 0.3064176  0.6330318  0.04208775]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.6330318

X_11200.jpeg
Predicting .................................
1/1 [==============================] - 

1/1 [==============================] - 0s 16ms/step
[[0.02594728 0.11421906 0.41815358 0.44168013]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.44168013

X_12400.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.03200628 0.1328735  0.36807406 0.4670461 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.4670461

X_13090.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.27407357 0.2024292  0.51852816 0.004969  ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.51852816

X_13100.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.16140175 0.64603627 0.19021873 0.00234322]]
1
Poor
The predicted profile is a Poor with accuracy = 0.64603627

X_13110.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.07403879 

1/1 [==============================] - 0s 16ms/step
[[0.00692544 0.03868283 0.10141607 0.85297567]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.85297567

X_20720.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00485125 0.02949894 0.08223569 0.8834141 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8834141

X_20730.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.00454656 0.02630498 0.08534974 0.8837987 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8837987

X_20740.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.00558359 0.03258478 0.09594485 0.8658867 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8658867

X_20750.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0033346

1/1 [==============================] - 0s 16ms/step
[[0.02418149 0.08271676 0.1830509  0.71005076]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.71005076

X_22910.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.05873153 0.13011126 0.25639123 0.554766  ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.554766

X_22920.jpeg
Predicting .................................
1/1 [==============================] - 0s 19ms/step
[[0.07341389 0.13956569 0.284602   0.5024184 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5024184

X_22950.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0235497  0.06320459 0.27128106 0.6419647 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6419647

X_22960.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.07508034

1/1 [==============================] - 0s 16ms/step
[[0.01700258 0.11305327 0.20398033 0.6659638 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6659638

X_24270.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01088419 0.10905889 0.13520312 0.7448538 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7448538

X_24280.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0183957  0.16652802 0.21218078 0.60289556]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.60289556

X_25110.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.16867031 0.39554438 0.36651993 0.06926536]]
1
Poor
The predicted profile is a Poor with accuracy = 0.39554438

X_25130.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.17505354 0.61906

1/1 [==============================] - 0s 16ms/step
[[0.00507707 0.04459856 0.08773713 0.8625873 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8625873

X_26020.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00621554 0.0650133  0.10473926 0.82403183]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.82403183

X_26030.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02775857 0.18160336 0.32855847 0.46207955]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.46207955

X_26080.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.01180786 0.11163774 0.1819795  0.69457483]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.69457483

X_26090.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01889

1/1 [==============================] - 0s 16ms/step
[[0.01772225 0.08720554 0.19352572 0.70154643]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.70154643

X_2810.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.0316738  0.14483458 0.27315915 0.5503325 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5503325

X_2820.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.04271919 0.19507833 0.32618117 0.43602133]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.43602133

X_6160.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.05065729 0.16315633 0.7370851  0.04910125]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.7370851

X_6170.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.0379

1/1 [==============================] - 0s 16ms/step
[[0.885085   0.07129733 0.04132625 0.00229141]]
0
Good
The predicted profile is a Good with accuracy = 0.885085

X_9700.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.00468455 0.14383936 0.1396803  0.7117958 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7117958

X_9710.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01824135 0.36730346 0.33018994 0.28426522]]
1
Poor
The predicted profile is a Poor with accuracy = 0.36730346

X_9720.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02511109 0.43623632 0.35799852 0.18065406]]
1
Poor
The predicted profile is a Poor with accuracy = 0.43623632

X_9730.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01878667 0.531271   0.3628744  0.0870679 

1/1 [==============================] - 0s 16ms/step
[[0.07851016 0.26006135 0.37034547 0.29108298]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.37034547

Y_240.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.07615512 0.25644532 0.3601482  0.30725133]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3601482

Y_250.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.07557891 0.284124   0.37648827 0.26380885]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.37648827

Y_25180.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.16914092 0.17747748 0.5179125  0.13546912]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.5179125

Y_25190.jpeg
Predicting .................................
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 16ms/step
[[0.18740489 0.23567078 0.3574249  0.21949947]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3574249

Y_28860.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.17365141 0.16139904 0.39175406 0.27319545]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.39175406

Y_28870.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.20463179 0.17646837 0.3724509  0.24644893]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.3724509

Y_28880.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.19400433 0.16077206 0.380579   0.26464465]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.380579

Y_28940.jpeg
Predicting .................................
1/1 [==============================] - 0

1/1 [==============================] - 0s 24ms/step
[[0.05579124 0.09387176 0.39418462 0.45615235]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.45615235

Y_30970.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.02490297 0.14912438 0.3004545  0.5255182 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5255182

Y_31280.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01238615 0.03594958 0.27080593 0.6808584 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6808584

Y_31300.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00259261 0.01597049 0.06174427 0.9196927 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.9196927

Y_31320.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0520012

1/1 [==============================] - 0s 16ms/step
[[0.14259061 0.25295925 0.2632464  0.3412038 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.3412038

Y_32690.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.19787082 0.31980407 0.23831216 0.2440129 ]]
1
Poor
The predicted profile is a Poor with accuracy = 0.31980407

Y_32700.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.23411839 0.32998624 0.25166243 0.1842329 ]]
1
Poor
The predicted profile is a Poor with accuracy = 0.32998624

Y_32720.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.32381025 0.37897444 0.20948839 0.0877269 ]]
1
Poor
The predicted profile is a Poor with accuracy = 0.37897444

Y_32730.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.2946029  0.35053283 0.2622536  0.09

1/1 [==============================] - 0s 16ms/step
[[0.20369981 0.30381212 0.29866204 0.19382605]]
1
Poor
The predicted profile is a Poor with accuracy = 0.30381212

Y_33310.jpeg
Predicting .................................
1/1 [==============================] - 0s 18ms/step
[[0.13297132 0.16901566 0.33227608 0.36573693]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.36573693

Y_33320.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.11548691 0.19444062 0.3093104  0.38076207]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.38076207

Y_33330.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.04934376 0.0850825  0.24165808 0.6239156 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6239156

Y_33340.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.08228536 0.1678

1/1 [==============================] - 0s 24ms/step
[[0.0195965  0.04942646 0.4335266  0.49745035]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.49745035

Y_35950.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0258359  0.1039464  0.4351808  0.43503687]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4351808

Y_36100.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03652003 0.11983313 0.29012936 0.55351746]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.55351746

Y_36110.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.02133739 0.06268371 0.2316571  0.6843218 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6843218

Y_36120.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.

1/1 [==============================] - 0s 16ms/step
[[0.02111193 0.05044158 0.40155765 0.52688885]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.52688885

Y_41000.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.017301   0.04417498 0.30948988 0.62903416]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.62903416

Y_41010.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01430522 0.04008269 0.29205868 0.6535533 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6535533

Y_41020.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01781624 0.04397421 0.3280944  0.6101152 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6101152

Y_41060.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.021127

1/1 [==============================] - 0s 16ms/step
[[0.09357636 0.557725   0.2942406  0.05445805]]
1
Poor
The predicted profile is a Poor with accuracy = 0.557725

Y_43510.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.0093401  0.041593   0.18009883 0.768968  ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.768968

Y_43520.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01025698 0.04332033 0.1823693  0.7640534 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7640534

Y_43530.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0092168  0.03695407 0.18084908 0.7729801 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7729801

Y_43540.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.00839518 0.03872033 

1/1 [==============================] - 0s 24ms/step
[[0.01955025 0.09985954 0.09489945 0.78569067]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.78569067

Y_44770.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03067239 0.12931733 0.10092738 0.739083  ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.739083

Y_44780.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02212673 0.10679472 0.08630571 0.7847728 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7847728

Y_44790.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.03881138 0.15401553 0.12693249 0.68024063]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.68024063

Y_44800.jpeg
Predicting .................................
1/1 [==============================] - 0s 20ms/step
[[0.0871565

1/1 [==============================] - 0s 16ms/step
[[0.01054105 0.06644934 0.11201243 0.8109971 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.8109971

Y_47130.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.07246836 0.23722765 0.1543755  0.5359285 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5359285

Y_47140.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.04524161 0.17644984 0.1436407  0.6346679 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6346679

Y_47150.jpeg
Predicting .................................
1/1 [==============================] - 0s 24ms/step
[[0.05147033 0.18821357 0.16880877 0.5915073 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.5915073

Y_47160.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02723825

1/1 [==============================] - 0s 16ms/step
[[0.06585936 0.18423001 0.26645857 0.48345208]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.48345208

Y_48320.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02681698 0.13095799 0.16029748 0.6819275 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6819275

Y_48340.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.01751799 0.08485823 0.16921525 0.7284086 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.7284086

Y_48350.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.02052512 0.09137679 0.1969091  0.6911891 ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.6911891

Y_48380.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.0011052

1/1 [==============================] - 0s 16ms/step
[[0.11118022 0.18101509 0.31476513 0.39303952]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.39303952

Y_50190.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.11895464 0.18474619 0.30894837 0.38735083]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.38735083

Y_50200.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.1386581  0.17307572 0.3322619  0.35600433]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.35600433

Y_50230.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.1852644  0.14325097 0.35370624 0.3177784 ]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.35370624

Y_50240.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[

1/1 [==============================] - 0s 16ms/step
[[0.06528927 0.20732944 0.40984234 0.31753895]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.40984234

Z_3000.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.06734822 0.14274463 0.4217723  0.36813492]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.4217723

Z_3020.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.07933543 0.13308793 0.45354345 0.33403322]]
2
Satisfactory
The predicted profile is a Satisfactory with accuracy = 0.45354345

Z_3040.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/step
[[0.04915244 0.08875804 0.40770045 0.454389  ]]
3
Very_Poor
The predicted profile is a Very_Poor with accuracy = 0.454389

Z_430.jpeg
Predicting .................................
1/1 [==============================] - 0s 16ms/ste

In [218]:
for elem in dict:
    print(elem,dict[elem],  dict[elem]/lenn*100)

Poor 417 12.950310559006212
Good 268 8.322981366459627
Satisfactory 1215 37.732919254658384
Very_Poor 1320 40.993788819875775
